spring: 
  datasource: 
    initialize: true
    driverClassName: com.mysql.jdbc.Driver 
    url: jdbc:mysql://goyaaaaaaaa.xyz:3306?useUnicode=true&characterEncoding=utf8 
    username: root
    password: open123
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    