spring: 
  datasource: 
    initialize: true
    driverClassName: com.mysql.jdbc.Driver 
    url: jdbc:mysql://goyaaaaaaaa.xyz:3306?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull 
    username: root
    password: open123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    